### ISSUE TITLE
Error while installing: "The package was not found with the source(s) listed."

### ISSUE THREAD

**Issue by day1player** [mandiant/commando-vm#122]
**Describe the bug and expected behavior**
Occasionally Windows will fail to resolve www.myget.org host immediately after restarting. This will cause a `The package was not found with the source(s) listed.` error as shown below
<img width="919" alt="image" src="https://user-images.githubusercontent.com/37482972/76254119-83988b80-6211-11ea-851e-1af11d6a8bee.png">

This can be fixed by simply restarting the install after the reboot completes:

1. Open powershell as administrator
2. navigate to the directory hosting the install script
3. `.\install.ps1 -nochecks 1`

**Comment by murrelljm99** [comment]
I found out what was causing this issue for me. The name of the user that was running the install script was "First Last", while the script was trying to write to "C:\Users\First" (instead of "C:\Users\First Last"). It would fail to install every single package with the error "The package was not found with the source(s) listed.". After a fresh install of Windows 10 (fully updated, username just "First"), the script has been working! I will give credit to whoever opened the issue in regards to Flare-VM, and was able to determine what was happening.
