### ISSUE TITLE
can make this support windows 10 home? 

### ISSUE THREAD

**Issue by scsdev-cyber** [mandiant/commando-vm#272]
Windows 10 home not able to finish the setup due to the defender antivirus not able to disable via the group police or something else, please check and confirm.

**Comment by day1player** [comment]
@scsdev-cyber simply put, since you cannot easily disable defender on Home editions, it will likely never be supported. You can download VMware Player for free, and you can download [a windows 10 VM](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) for free as well, which is an Enterprise edition and thus can have defender disabled.
