### ISSUE TITLE
Error First step installing

### ISSUE THREAD

**Issue by Redcell202** [mandiant/commando-vm#277]
Hello,

when I type intall.ps1 I get this message

![ErrorInstallPS1](https://user-images.githubusercontent.com/105014095/167003678-46631518-e879-4324-bd34-03a1241388a9.PNG)

Hope Its a stupid thing but I don´t know how can I solve it

**Comment by mjw10086** [comment]
That's because 'https://boxstarter.org/bootstrapper.ps1' the file is missing , response 404. You can replace the url to a avaliable one. Just modify the install script

**Comment by day1player** [comment]
@Redcell202 make sure in github you are downloading the source for the file, it looks like you downloaded the HTML along with the install script. There is a little button that says "Raw" 
<img width="321" alt="image" src="https://user-images.githubusercontent.com/37482972/167021336-a5e7afe4-99f6-4c4f-8d9f-1cd81e266ad6.png">
You should be using that button if you want to just download the script. Otherwise, you can download the full zip and unzip. the install script will be in there

**Comment by day1player** [comment]
Make sure you are following the install instructions carefully 😄 https://github.com/mandiant/commando-vm#instructions

**Comment by mjw10086** [comment]
I just run successfully , replace the url by 'https://raw.githubusercontent.com/chocolatey/boxstarter/master/BuildScripts/bootstrapper.ps1'  in line 196 , or just run 
`iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/chocolatey/boxstarter/master/BuildScripts/bootstrapper.ps1')); get-boxstarter -Force ` and comment out the line 196 , then run.

**Comment by Antiseci** [comment]
> 


您好请关注一下https://github.com/mandiant/commando-vm/issues/276 ，急需解决方案谢谢
Hello, please pay attention https://github.com/mandiant/commando-vm/issues/276 , urgent solutions thank you

**Comment by Antiseci** [comment]
Hello, please pay attention https://github.com/mandiant/commando-vm/issues/276 , urgent solutions thank you

**Comment by Antiseci** [comment]
> 确保您仔细遵循安装说明😄 https://github.com/mandiant/commando-vm#instructions

Hello, please pay attention https://github.com/mandiant/commando-vm/issues/276 , urgent solutions thank you

**Comment by Menn1s** [comment]
Feel free to open another issue if you're still running into problems. Closing because of age
