### ISSUE TITLE
Why Metasploit from Rapid7 was missed

### ISSUE THREAD

**Issue by IAMinZoho** [mandiant/commando-vm#297]
Thanks for releasing the V3.0! Very excited to see a GUI but very disappointed that Metasploit is not installed. Metasploit has always been the defacto C2 framework for Kali back from the days when it was known as Backtrack. Why them miss a powerful tool like Metasploit in Commado VM?

Team Commando, If you have any suggestions please let me know.

Thank you once again and hats off to the entire team!

**Comment by day1player** [comment]
We have a metasploit.vm packages currently, our issue is the way that they are doing their releases makes it difficult to keep our package updated. They release everything under "latest" which then breaks our package since the hashes change. Currently 

Now tracking at https://github.com/mandiant/VM-Packages/issues/633
