### ISSUE TITLE
Stupid question... how do I know it installed correctly? 

### ISSUE THREAD

**Issue by mathurin68** [mandiant/commando-vm#305]
I see the "Commando VM" graphic and the 'Tools' folder is in there... but 'cup all' doesn't seem to work, it doesn't seem to recognize 'cinst' 
![image](https://github.com/mandiant/commando-vm/assets/5932961/18bd1282-9d80-4b0e-a717-9ac88a062e88)

But a lot of stuff does seem to be there - 
```
COMMANDO 08/28/2023 08:05:23
PS C:\Windows\system32 > Import-module C:\Tools\PowerSploit\Recon\PowerView.ps1
COMMANDO 08/28/2023 08:05:44
PS C:\Windows\system32 >
```

Thank you for building this!!

**Comment by day1player** [comment]
@mathurin68 good question! I'm not sure exactly when but Chocolatey removed those shortened commands, so instead of `cinst` it will be `choco install` and instead of `cup` it will be `choco update`.. 

To answer your question, when the install completes the installer package will play a little sound and it will pop up a log file of all of the failed packages for you to inspect.. There will also be a pop-up dialog box that tells you the install is complete. You can check this file in  `%programdata%\_vm\log.txt `. All of your installed packages will also be listed in `%programdata%\chocolatey\lib\` (failed packages will be in `lib-bad`)..

Some more indicators that the install finished are that there is a `Tools` folder and a `PS_Transcripts` folder on the Desktop, and that your hostname has been changed to `commando` and your powershell and cmd prompts have the timestamp on them.

**Comment by mathurin68** [comment]
Perfect, thank you for the quick response, and got it!
