### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by sassykenzie1** [mandiant/commando-vm#308]
Tried both choco uninstall commandovm.win10.installer.fireeye and the stuff in https://chocolatey.org/docs/uninstallation.

Neither worked. Is it possible to get rid of it, or is it there permanently? The only system restore created automatically was created **after** I installed it.

**Comment by nos3curity** [comment]
Since CommandoVM is meant to only be installed on a virtual machine, the uninstall scripts are best-effort. 

If you intend to upgrade from an older CommandoVM build to the new one, you will need a clean VM, so we recommend rolling back a snapshot or wiping and reinstalling your OS if for some reason you're running it on your host.
