### ISSUE TITLE
Tool request - Prebellico

### ISSUE THREAD

**Issue by williamcaput** [mandiant/commando-vm#48]
Prebellico (Passive reconnaissance)
https://github.com/unixrox/prebellico

**Comment by day1player** [comment]
Did you already install this onto Commando?

**Comment by williamcaput** [comment]
I did.  Just thought it would be a nice tool to add to the default distro. 

Sent from Yahoo Mail on Android 
 
  On Fri, Jun 21, 2019 at 12:36, day1player<notifications@github.com> wrote:   
Did you already install this onto Commando?

**Comment by day1player** [comment]
Ok, good to know. It's not as easy to install as I was thinking, it's on the list still but probably going to wait until the next update in August 😄

**Comment by Menn1s** [comment]
Closing because of changes to the structure of Commando VM and the age of the issue. We are currently working through more core/fundamental changes to the project.

If you would still like this package to be included, please create an issue on the https://github.com/mandiant/VM-Packages repo. Thanks
